source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'validates_timeliness', '~> 3.0'
gem 'simple_form'
gem 'will_paginate'
gem 'carrierwave'
gem 'nested_form'
gem 'tconsole', '1.2.8'
gem 'lazy_high_charts'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# Additional gems that are very useful in Rails development
group :development do
  gem 'quiet_assets'
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'wirble'
  gem 'hirb'
  gem 'faker'
end

# Gems used only in testing
group :test do
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'mocha', require: false
  gem 'simplecov'
  gem 'turn'
  gem 'single_test'
end

group :development, :test do
  gem 'factory_girl_rails'
end
