development:
  adapter: postgresql
  database: development
  username: Sam # replace this with your own user name
  password: Fya2mB!r # replace this with your own password
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000